"""Initial migration

Revision ID: ffc05ed927fa
Revises: 
Create Date: 2025-12-05 14:01:18.055193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc05ed927fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnpj_uo',
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('uo_contribuinte', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cnpj')
    )
    op.create_table('codigo_aba',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('aba', sa.String(), nullable=False),
    sa.CheckConstraint("aba IN ('servidor', 'patronal-gilrat')", name='check_aba'),
    sa.PrimaryKeyConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codigo_aba')
    op.drop_table('cnpj_uo')
    # ### end Alembic commands ###
